### Obtenemos los animes y usuarios de la base de datos

In [2]:
import pymongo
client = pymongo.MongoClient('mongodb://anal:anal18@18.220.137.254/anal')
db = client['anal']

In [3]:
usersdb = db['users']
animesdb = db['animes']
tagsdb = db['tags']

In [18]:
animes = animesdb.find({ }).count()
tags = tagsdb.find({ }).count()
users = usersdb.find({ }).count()

In [5]:
print(animes)
print(tags)
print(users)

6398
405
2854


_____

### Dataset de usuarios

In [6]:
import pandas as pd
users= usersdb.find()
usersdf = pd.DataFrame(list(users))

In [7]:
usersdf.head()

_id age                                             animes  \
0     sothis  37  [{'animeId': 1, 'ratingUser': 0}, {'animeId': ...   
1     Slayer  40  [{'animeId': 970, 'ratingUser': 5.0}, {'animeI...   
2    DistMan  35  [{'animeId': 970, 'ratingUser': 0}, {'animeId'...   
3  Modesty81  37  [{'animeId': 5, 'ratingUser': 2.5}, {'animeId'...   
4    Nanashi  35  [{'animeId': 15, 'ratingUser': 0}, {'animeId':...   

   animesSeen  gender  
0         969  Female  
1         133    Male  
2         381    Male  
3         314  Female  
4         192  Female

In [8]:
len(usersdf['animes'][0])

969

### Dataset de animes

In [9]:
animes= animesdb.find()
animesdf = pd.DataFrame(list(animes))
animesdf = animesdf.drop('rating',1).rename(index=str, columns={"_id": "animeId"})

In [10]:
animesdf.head()

animeId                                               tags  \
0        1  [Fantasy, Romance, Abstract, Dream World, Midd...   
1        2  [Comedy, Ecchi, Fantasy, Seinen, Superpowers, ...   
2        3                                                 []   
3        4  [Comedy, CG Animation, Crude, Original Work, S...   
4        5  [Action, Fantasy, Seinen, Demons, Magic, Expli...   

                                   title  
0                            1001 Nights  
1                         11eyes Special  
2                 2005-nen Uchuu no Tabi  
3  3D Onara Gorou ga Dance Dance Dance!!  
4                             3 x 3 Eyes

In [20]:
animes2 = animesdb.find()
animesdf2 = pd.DataFrame(list(animes2))
animesdf2 = animesdf2.drop('tags',1).drop('rating',1).rename(index=str, columns={"_id": "animeId"})

In [21]:
animesdf2.head()

animeId                                  title
0        1                            1001 Nights
1        2                         11eyes Special
2        3                 2005-nen Uchuu no Tabi
3        4  3D Onara Gorou ga Dance Dance Dance!!
4        5                             3 x 3 Eyes

### Dataset animeID/raitingUser/userID

In [12]:
animesWdf=  pd.DataFrame(list(usersdf.iloc[0]['animes']))
animesWdf['userId']=0
animesWdf['userNick']=usersdf.iloc[0]['_id']
 
cantUsers=len(usersdf)-1 #-1 del primer usuario analizado arriba
for i in range(cantUsers):
    xd=  pd.DataFrame(list(usersdf.iloc[i+1]['animes']))
    xd['userId']=i+1
    xd['userNick']=usersdf.iloc[i+1]['_id']
    animesWdf = pd.concat([animesWdf, xd],ignore_index=True)

In [13]:
animesWdf.head()

animeId  ratingUser  userId userNick
0        1         0.0       0   sothis
1        2         4.0       0   sothis
2        3         2.0       0   sothis
3        4         0.5       0   sothis
4        5         3.0       0   sothis

___

# Sistema de recomendación

In [14]:
import numpy as np

### Tabla pivot

In [22]:
ratings = pd.merge(animesdf2, animesWdf)
ratings.head()

animeId        title  ratingUser  userId        userNick
0        1  1001 Nights         0.0       0          sothis
1        1  1001 Nights         4.0      42       karplusan
2        1  1001 Nights         1.0      91       AnarchicQ
3        1  1001 Nights         0.0     123  KeeperofDemons
4        1  1001 Nights         0.0     184         Sythlia

In [129]:
R_df = animesWdf.pivot_table(index=['userId'],columns=['animeId'],values='ratingUser').fillna(0)
R_df.head()

animeId  1     2     3     4     5     6     7     8     9     10    ...   \
userId                                                               ...    
0         0.0   4.0   2.0   0.5   3.0   0.0   3.5   0.0   3.5   2.0  ...    
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
3         0.0   0.0   0.0   0.0   2.5   2.5   0.0   0.0   0.0   0.0  ...    
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    

animeId  6389  6390  6391  6392  6393  6394  6395  6396  6397  6398  
userId                                                               
0         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 6398 columns]

In [99]:
R = R_df.as_matrix()
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

In [144]:
len(user_ratings_mean)

2854

In [130]:
print(len(R_demeaned[0]))
print(len(R_demeaned))

6398
2854


In [153]:
R_demeaned

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

## Singular Value Decomposition

In [155]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 10)

/home/gina_bustamante/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
/home/gina_bustamante/anaconda3/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:1781: RuntimeWarning: invalid value encountered in greater
  above_cutoff = (eigvals > cutoff)


In [150]:
print(len(U))
print(len(U[0]))

2854
10


In [151]:
print(len(sigma))
sigma

10


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [132]:
sigma = np.diag(sigma)

In [133]:
sigma

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Haciendo predicciones

In [154]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = R_df.columns)

ValueError: shapes (2854,) and (10,6398) not aligned: 2854 (dim 0) != 10 (dim 0)

In [126]:
preds_df[499].dropna()

Series([], Name: 499, dtype: float64)

### Haciendo recomendaciones

In [ ]:
rename(columns = {499: 'Predictions'}).sort_values('Predictions', ascending = True).iloc[:num_recommendations, :-1])


In [86]:
def recommend_animes(predictions_df, userID, animes_df, original_ratings_df, num_recommendations=5):
    # Obtenemos y ordenamo las predicciones de cada usuario
    user_row_number = userID - 1 # UserID starts at 1, not 0
    print(user_row_number)
    
    sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)
    #print(sorted_user_predictions)
    
    for i in sorted_user_predictions:
        if (i!='nan'):
            print(i)
    
    
    # Obtener los datos del usuario ya gregar la información del anime
    user_data = original_ratings_df[original_ratings_df.userId == (userID)]
    user_full = (user_data.merge(animes_df, how = 'left', left_on = 'animeId', right_on = 'animeId').
                     sort_values(['ratingUser'], ascending=False))
    
    #print(user_full)
    print('El usuario {0} ya ha puntuado {1} animes.'.format(userID, user_full.shape[0]))
    print('{0} Animes con los puntajes predecidos mas altos'.format(num_recommendations))
    
    # Recomendar los animes con los valores predecidos mas altos que el usuario todavía no ha visto
    recommendations = (animes_df[~animes_df['animeId'].isin(user_full['animeId'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'animeId',
               right_on = 'animeId').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = True).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

### Pruebas

In [87]:
already_rated, predictions = recommend_animes(preds_df, 500, animesdf, animesWdf, 20)

499
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan


nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan


In [78]:
already_rated.head(10)

animeId  ratingUser  userId  userNick  \
102      186         5.0     500  Hatake86   
60       983         5.0     500  Hatake86   
280     2105         5.0     500  Hatake86   
447     2185         5.0     500  Hatake86   
448     2186         5.0     500  Hatake86   
602     2036         5.0     500  Hatake86   
454     1463         5.0     500  Hatake86   
64      1242         5.0     500  Hatake86   
149     1333         5.0     500  Hatake86   
455     1878         5.0     500  Hatake86   

                                                  tags  \
102  [Mystery, Shounen, Criminals, Detectives, Mind...   
60   [Action, Shounen, Shinigami, Supernatural, Swo...   
280  [Action, Adventure, Shounen, Superpowers, Viol...   
447  [Comedy, Shounen, Dancing, Pirates, Shorts, Ba...   
448  [Comedy, Shounen, Sports, Pirates, Shorts, Soc...   
602  [Horror, Seinen, Police, Explicit Violence, Nu...   
454  [Action, Adventure, Fantasy, Shounen, Pirates,...   
64   [Action, Fantasy, Mystery, Master-Servant Rela...   
149  [Action, Shounen, Afterlife, Hell, Martial Art...   
455    [Adventure, Shounen, Pirates, Based on a Manga]   

                                             title  
102                                     Death Note  
60       Bleach Movie 2: The DiamondDust Rebellion  
280                         Hunter x Hunter (2011)  
447             One Piece: Django's Dance Carnival  
448                  One Piece: Dream Soccer King!  
602                                          Tokko  
454                              One Piece Movie 1  
64                                          Blood+  
149          Dragon Ball Z Movie 12: Fusion Reborn  
455  One Piece Movie 2: Clockwork Island Adventure

In [79]:
predictions

animeId                                               tags  \
0         1  [Fantasy, Romance, Abstract, Dream World, Midd...   
1         2  [Comedy, Ecchi, Fantasy, Seinen, Superpowers, ...   
2         3                                                 []   
3         4  [Comedy, CG Animation, Crude, Original Work, S...   
4         7  [Drama, Romance, Childhood Friends, Original W...   
5         8             [Environmental, Original Work, Shorts]   
6         9  [Action, Sci Fi, Shounen, Cyborgs, Police, Sup...   
7        10  [Action, Comedy, Ecchi, Shounen, Gangs, Hand t...   
8        11  [Drama, Shoujo, Sports, School Life, Tennis, B...   
9        12         [Adventure, Fantasy, Magic, Original Work]   
10       13       [Animal Protagonists, Dogs, Family Friendly]   
11       14  [Comedy, Seinen, Agriculture, Chibi, Robots, S...   
12       16                                           [Shorts]   
13       17  [Sci Fi, Seinen, Cyberpunk, Psychic Powers, Su...   
14       18  [Drama, Fantasy, Romance, Illness, Based on an...   
15       19             [Drama, Romance, Music, Original Work]   
16       21  [Adventure, Fantasy, Family Friendly, Journey ...   
17       22  [Adventure, Family Friendly, Middle Eastern, B...   
18       23  [Sci Fi, Seinen, Aliens, Psychological, School...   
19       24                                  [Action, Fantasy]   

                                     title  
0                              1001 Nights  
1                           11eyes Special  
2                   2005-nen Uchuu no Tabi  
3    3D Onara Gorou ga Dance Dance Dance!!  
4                 5 Centimeters per Second  
5                                   663114  
6                              8 Man After  
7                          Abashiri Family  
8                      Ace wo Nerae! Movie  
9   Adventures of Horus: Prince of the Sun  
10                                Afro-ken  
11                      Agriculture Girls!  
12                               Ai (2012)  
13                                 Ai City  
14                               Air Movie  
15                 Ajimu Kaigan Monogatari  
16                      Alakazam the Great  
17          Ali Baba to 40-hiki no Touzoku  
18                              Alien Nine  
19                   amazarashi: Christmas